### ISSUE TITLE
ValueError: plaintext is too long

### ISSUE THREAD

**Issue by jtleniger** [simon-weber/gpsoauth#17]
I have a pretty lengthy password and receive this exception when trying to login.

**Comment by simon-weber** [comment]
Huh, that's a new one. Can you provide a traceback? I'm not sure off the top of my head where this would be coming from.

**Comment by jtleniger** [comment]
I think I must have pasted my password more than once on accident. Can't reproduce with my actual password, but if I paste it 2-3 times:

`Traceback (most recent call last):
  File "ImportList.py", line 193, in <module>
    api = open_api()
  File "D:\gmusic-playlist\common.py", line 181, in open_api
    if not api.login(username, password, Mobileclient.FROM_MAC_ADDRESS):
  File "C:\python27\lib\site-packages\gmusicapi\clients\mobileclient.py", line 122, in login
    if not self.session.login(email, password, android_id):
  File "C:\python27\lib\site-packages\gmusicapi\session.py", line 191, in login
    res = gpsoauth.perform_master_login(email, password, android_id)
  File "C:\python27\lib\site-packages\gpsoauth\__init__.py", line 60, in perform_master_login
    'EncryptedPasswd': google.signature(email, password, android_key_7_3_29),
  File "C:\python27\lib\site-packages\gpsoauth\google.py", line 50, in signature
    encrypted_login = cipher.encrypt((email + u'\x00' + password).encode('utf-8'))
  File "C:\python27\lib\site-packages\Cryptodome\Cipher\PKCS1_OAEP.py", line 141, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.`

Can probably close this unless it happens on someone's real password.

**Comment by simon-weber** [comment]
Ah, ok, that makes sense. We can check the size of the key to find the max plaintext length, and see if anybody has looked into what Google does to handle longer plaintext (probably some kind of chunking?).

**Comment by jackwilsdon** [comment]
I can reproduce this with a long password (64 characters long).

**Comment by simon-weber** [comment]
Gotcha. There's a mention of an 80-char username+password limit in [the blog post I based my code on](http://codedigging.com/blog/2014-06-09-about-encryptedpasswd/), but it's not immediately clear to me how to work around it.

**Comment by jackwilsdon** [comment]
I'm not sure of how much use this is, but I've managed to decompile the class mentioned in that post from an old version of GSF from 2014;

```Java
package com.google.android.gsf.loginservice;

import android.content.ContentResolver;
import android.util.Base64;
import android.util.Log;
import com.google.android.gsf.Gservices;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.RSAPublicKeySpec;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;

class PasswordEncrypter
{
  private static char[] HEX_CHARS = { 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 97, 98, 99, 100, 101, 102 };
  
  private static String computeSha1Hash(String paramString)
  {
    try
    {
      paramString = MessageDigest.getInstance("SHA-1").digest(paramString.getBytes("UTF-8"));
      StringBuffer localStringBuffer = new java/lang/StringBuffer;
      localStringBuffer.<init>();
      for (int i = 0; i < paramString.length; i++)
      {
        localStringBuffer.append(HEX_CHARS[((paramString[i] & 0xFF) >>> 4)]);
        localStringBuffer.append(HEX_CHARS[(paramString[i] & 0xFF & 0xF)]);
      }
      paramString = localStringBuffer.toString();
      return paramString;
    }
    catch (NoSuchAlgorithmException paramString)
    {
      throw new RuntimeException(paramString);
    }
    catch (UnsupportedEncodingException paramString)
    {
      throw new RuntimeException(paramString);
    }
  }
  
  public static PublicKey createKeyFromString(String paramString, byte[] paramArrayOfByte)
  {
    try
    {
      Object localObject2 = Base64.decode(paramString, 0);
      int j = readInt((byte[])localObject2, 0);
      Object localObject1 = new byte[j];
      System.arraycopy(localObject2, 4, localObject1, 0, j);
      paramString = new java/math/BigInteger;
      paramString.<init>(1, (byte[])localObject1);
      int i = readInt((byte[])localObject2, j + 4);
      byte[] arrayOfByte = new byte[i];
      System.arraycopy(localObject2, j + 8, arrayOfByte, 0, i);
      localObject1 = new java/math/BigInteger;
      ((BigInteger)localObject1).<init>(1, arrayOfByte);
      localObject2 = MessageDigest.getInstance("SHA-1").digest((byte[])localObject2);
      paramArrayOfByte[0] = 0;
      System.arraycopy(localObject2, 0, paramArrayOfByte, 1, 4);
      localObject2 = KeyFactory.getInstance("RSA");
      paramArrayOfByte = new java/security/spec/RSAPublicKeySpec;
      paramArrayOfByte.<init>(paramString, (BigInteger)localObject1);
      paramString = ((KeyFactory)localObject2).generatePublic(paramArrayOfByte);
    }
    catch (NoSuchAlgorithmException paramString)
    {
      throw new RuntimeException(paramString);
    }
    catch (InvalidKeySpecException paramString)
    {
      for (;;)
      {
        Log.e("GoogleLoginService.PasswordEncrypter", "received bad google_login_public_key: ", paramString);
        paramString = null;
      }
    }
    return paramString;
  }
  
  public static String encryptPassword(ContentResolver paramContentResolver, String paramString1, String paramString2)
  {
    return encryptPassword(paramString1, paramString2, paramContentResolver, null);
  }
  
  private static String encryptPassword(String paramString1, String paramString2, ContentResolver paramContentResolver, String paramString3)
  {
    return encryptString(paramString1 + "\000" + paramString2, paramContentResolver, paramString3);
  }
  
  private static String encryptString(String paramString1, ContentResolver paramContentResolver, String paramString2)
  {
    PublicKey localPublicKey;
    if (paramString2 != null)
    {
      paramContentResolver = paramString2;
      paramString2 = paramContentResolver;
      if (paramContentResolver == null)
      {
        Log.i("GoogleLoginService.PasswordEncrypter", "no public key available, using default");
        paramString2 = "AAAAgMom/1a/v0lblO2Ubrt60J2gcuXSljGFQXgcyZWveWLEwo6prwgi3iJIZdodyhKZQrNWp5nKJ3srRXcUW+F1BD3baEVGcmEgqaLZUNBjm057pKRI16kB0YppeGx5qIQ5QjKzsR8ETQbKLNWgRY0QRNVz34kMJR3P/LgHax/6rmf5AAAAAwEAAQ==";
      }
      paramContentResolver = new byte[5];
      localPublicKey = createKeyFromString(paramString2, paramContentResolver);
      if (localPublicKey != null) {
        break label53;
      }
      paramString1 = null;
    }
    for (;;)
    {
      return paramString1;
      paramContentResolver = Gservices.getString(paramContentResolver, "google_login_public_key");
      break;
      try
      {
        label53:
        paramString2 = Cipher.getInstance("RSA/ECB/OAEPWITHSHA1ANDMGF1PADDING");
        byte[] arrayOfByte2 = paramString1.getBytes("UTF-8");
        int k = (arrayOfByte2.length - 1) / 86 + 1;
        byte[] arrayOfByte1 = new byte[k * 133];
        int i = 0;
        if (i < k)
        {
          paramString2.init(1, localPublicKey);
          if (i == k - 1) {}
          for (int j = arrayOfByte2.length - i * 86;; j = 86)
          {
            paramString1 = paramString2.doFinal(arrayOfByte2, i * 86, j);
            System.arraycopy(paramContentResolver, 0, arrayOfByte1, i * 133, paramContentResolver.length);
            System.arraycopy(paramString1, 0, arrayOfByte1, i * 133 + paramContentResolver.length, paramString1.length);
            i++;
            break;
          }
        }
        paramString1 = Base64.encodeToString(arrayOfByte1, 10);
      }
      catch (NoSuchAlgorithmException paramString1)
      {
        throw new RuntimeException(paramString1);
      }
      catch (NoSuchPaddingException paramString1)
      {
        throw new RuntimeException(paramString1);
      }
      catch (BadPaddingException paramString1)
      {
        throw new RuntimeException(paramString1);
      }
      catch (UnsupportedEncodingException paramString1)
      {
        throw new RuntimeException(paramString1);
      }
      catch (IllegalBlockSizeException paramString1)
      {
        Log.e("GoogleLoginService.PasswordEncrypter", "error encrypting password: ", paramString1);
        paramString1 = null;
      }
      catch (InvalidKeyException paramString1)
      {
        Log.e("GoogleLoginService.PasswordEncrypter", "received bad google_login_public_key: ", paramString1);
        paramString1 = null;
      }
    }
  }
  
  public static String hashPassword(String paramString1, String paramString2)
  {
    if (paramString1 == null) {
      Log.wtf("GoogleLoginService.PasswordEncrypter", "attempt to hash null username");
    }
    if (paramString1.equals("null")) {
      Log.wtf("GoogleLoginService.PasswordEncrypter", "attempt to hash \"null\" username");
    }
    if (paramString2 == null) {
      Log.wtf("GoogleLoginService.PasswordEncrypter", "attempt to hash null password");
    }
    if (paramString2.equals("null")) {
      Log.wtf("GoogleLoginService.PasswordEncrypter", "attempt to hash \"null\" password");
    }
    paramString2 = paramString1 + "\000" + paramString2 + "\000" + paramString1;
    paramString1 = computeSha1Hash(paramString2);
    paramString2 = encryptString(paramString2, null, "AAAAgMom/1a/v0lblO2Ubrt60J2gcuXSljGFQXgcyZWveWLEwo6prwgi3iJIZdodyhKZQrNWp5nKJ3srRXcUW+F1BD3baEVGcmEgqaLZUNBjm057pKRI16kB0YppeGx5qIQ5QjKzsR8ETQbKLNWgRY0QRNVz34kMJR3P/LgHax/6rmf5AAAAAwEAAQ==");
    if (paramString2 == null) {}
    for (;;)
    {
      return paramString1;
      paramString1 = paramString1 + ";" + paramString2;
    }
  }
  
  private static int readInt(byte[] paramArrayOfByte, int paramInt)
  {
    return 0x0 | (paramArrayOfByte[paramInt] & 0xFF) << 24 | (paramArrayOfByte[(paramInt + 1)] & 0xFF) << 16 | (paramArrayOfByte[(paramInt + 2)] & 0xFF) << 8 | paramArrayOfByte[(paramInt + 3)] & 0xFF;
  }
}
```

That code probably won't compile out of the box due to the fact it's decompiled from an APK, but hopefully it might be a starting point.

**Comment by jackwilsdon** [comment]
[Managed to find a JS implementation of the login details encryption too, which is probably more useful.](https://github.com/dweinstein/node-google-play/blob/e1d66c2f7f65afd8c373e65be59848de8b660be3/lib/login.js).

**Comment by jackwilsdon** [comment]
Just spent the last 30 minutes reverse-engineering the original Java source from Android from 2014, and it seems that it also has the 80 character combined limitation!

I did some more research, and it looks like authentication has changed how it works for these services, as linking a Google account to your device uses [this URL](http://accounts.google.com/embedded/setup/v2/android) for setup now. I've not looked into how it stores the authentication token or uses it with Google Play Services though.

**Comment by simon-weber** [comment]
Interesting. Nice work!

**Comment by PaddyMac** [comment]
Have you looked into this any further? Google has details about it's OAuth implementation at https://developers.google.com/identity/protocols/oauth2

**Comment by derekantrican** [comment]
I can reproduce this even with my "short" password (12 characters). I'm just following the instructions at the README: https://github.com/simon-weber/gpsoauth/blob/master/README.md#alternative-flow

Here's my code (sanitized a bit, of course):

```python
email = '[email]'
token = '[oauth_token]'
android_id = '[device_id]'

print('perform_master_login')

master_response = gpsoauth.perform_master_login(email, token, android_id)
master_token = master_response['Token']
```

And here's the exception thrown with stack trace:

```
Traceback (most recent call last):
  File "C:\Users\derek\Desktop\GKeepToGmail\syncNotes.py", line 63, in <module>
    master_response = gpsoauth.perform_master_login(email, token, android_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gpsoauth\__init__.py", line 141, in perform_master_login
    "EncryptedPasswd": google.construct_signature(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gpsoauth\google.py", line 58, in construct_signature
    encrypted_login = cipher.encrypt((email + "\x00" + password).encode("utf-8"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\Cryptodome\Cipher\PKCS1_OAEP.py", line 117, in encrypt
    raise ValueError("Plaintext is too long.")
ValueError: Plaintext is too long.
```

I have 2FA on - don't know if that matters using the oauth token, though

**Comment by jackwilsdon** [comment]
@derekantrican is your email + password combination around 80 characters? The limit is for both combined.

**Comment by derekantrican** [comment]
No. However, I think I found later that I should be using `exchange_token` instead of `perform_master_login`. I think I was trying to use the oauth token for `perform_master_login` instead of the "master token"
